config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get '/my_requests' => 'home#index'

  resources :contractor_requests
  resources :labor_requests
  resources :staff_requests

  resources :users
  get '/logout' => 'users#logout'
  get 'impersonate/user/:user_id' => 'impersonate#create', as: :impersonate_user
  delete 'impersonate/revert' => 'impersonate#destroy', as: :revert_impersonate_user

  resources :organizations
  resources :organization_cutoffs
  resources :review_statuses
  resources :links

  resources :reports
  get '/reports/:id/download' => 'reports#download', as: :report_download

  get '/ping' => 'ping#verify'
end

app/controllers/review_statuses_controller.rb
# frozen_string_literal: true

class ReviewStatusesController < ApplicationController
  before_action :set_review_status, only: %i[show edit update destroy]
  after_action :verify_authorized

  # GET /review_status
  def index
    authorize ReviewStatus
    @review_statuses = ReviewStatus.all.paginate(page: params[:page])
  end

  # GET /review_status/1
  def show
    authorize @review_status
  end

  # GET /review_status/new
  def new
    authorize ReviewStatus
    @review_status = ReviewStatus.new
  end

  # GET /review_status/1/edit
  def edit
    authorize @review_status
  end

  # POST /review_status
  def create
    authorize ReviewStatus
    @review_status = ReviewStatus.new(review_status_params)
    respond_to do |format|
      if @review_status.save
        format.html { redirect_to @review_status, notice: "Review Status #{@review_status.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /review_status/1
  def update
    authorize @review_status
    respond_to do |format|
      if @review_status.update(review_status_params)
        format.html { redirect_to @review_status, notice: "Review Status #{@review_status.name} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /review_status/1
  def destroy
    authorize ReviewStatus
    if @review_status.destroy
      flash[:notice] = "Review status #{@review_status.name} was successfully deleted."
    else
      flash[:error] = "ERROR Deleting #{@review_status.name} #{@review_status.errors}"
    end
    respond_to do |format|
      format.html { redirect_to review_statuses_url }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_review_status
      @review_status = ReviewStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_status_params
      params.require(:review_status).permit(:name, :code, :color)
    end
end

app/views/review_statuses/_form.html.erb
<div class='container'>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
	    <%= simple_form_for @review_status do |f| %>
	

        <div class="page-header">
          <h2><%= @review_status.name %> <small>Review Status</small>
            <div class="pull-right">
              <% if edit_or_new? %> 
                <%= link_to 'Back', review_statuses_path, class: 'btn btn-default' %>
                <%= f.submit 'Save', class: 'btn btn-success' %>
              <% elsif show? %>
                <%= link_to 'Edit', edit_review_status_path(@review_status.id), class: 'btn btn-success' %>
              <% end %>
            </div>
          </h2>
        </div>
  
	
		    <%= render 'shared/form_errors', errors: @review_status.errors %>
  
        <div class='panel panel-default'>
          <div class="panel-body">
              <%= f.input :name, disabled: !edit_or_new?  %>
              <%= f.input :code, disabled: !edit_or_new?  %>
              <%= f.input :color, as: :color, type: :color,  disabled: !edit_or_new?  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/review_statuses/index.html.erb
<div class='container'>

  <div class="page-header">
    <h1>Review Statuses
      <span class='pull-right'><%= link_to( "New", new_review_status_path, class: "btn btn-success" ) %></span>
    </h1>
  </div>
  
  <div class="btn-toolbar pagination">
    <div class='btn-group'><%= will_paginate( @review_statuses, renderer: BootstrapPagination::Rails) %></div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Color</th> 
        <th></th> 
      </tr>
    </thead>

    <tbody>
      <% @review_statuses.each do |status| %>
        <%= content_tag :tr, id: "status_#{status.id}" do %>
          <td><%= status.name %></td>
          <td><%= status.code %></td>
          <td>
            <input value="<%= status.color %>" 
                   readonly="readonly" disabled="disabled" 
                                       name="review_status[color]" id="<%= status.id %>_color" type="color"> 
          </td> 
          <%= render 'shared/index_action_buttons', object: status %> 
        <% end %>
      <% end %>
    </tbody>

  </table>
</div>

app/views/review_statuses/new.html.erb
<%= render 'shared/new_or_edit', title: "Review Status" %>

app/views/review_statuses/show.html.erb
<%= render 'form' %>