config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get '/my_requests' => 'home#index'

  resources :contractor_requests
  resources :labor_requests
  resources :staff_requests

  resources :users
  get '/logout' => 'users#logout'
  get 'impersonate/user/:user_id' => 'impersonate#create', as: :impersonate_user
  delete 'impersonate/revert' => 'impersonate#destroy', as: :revert_impersonate_user

  resources :organizations
  resources :organization_cutoffs
  resources :review_statuses
  resources :links

  resources :reports
  get '/reports/:id/download' => 'reports#download', as: :report_download

  get '/ping' => 'ping#verify'
end

app/models/organization.rb
# frozen_string_literal: true

# The Organization the the request is associated to
class Organization < ApplicationRecord
  include Cutoffable
  include Resettable
  include Flattenable

  class << self
    def policy_class
      AdminOnlyPolicy
    end

    def root_org
      root.first
    end
  end

  belongs_to :parent, class_name: 'Organization', foreign_key: 'organization_id',
                      optional: true, inverse_of: :children
  validates :organization_id, presence: true, unless: :root?

  has_many :children, foreign_key: :organization_id, class_name: 'Organization', inverse_of: :parent,
                      dependent: :restrict_with_error
  # a more basic AR way of getting children
  has_many :organizations, dependent: :restrict_with_error

  # a weird one. Rubocop wants use to have a dependent, but we don't want one
  # actually. This is bc our has_one here is just some "association trickery",
  # because the forign_key is being set to the cutoff :organization_type. When
  # the org record is deleted, we shouldn't do anything to the Cutoff.
  # rubocop:disable Rails/HasManyOrHasOneDependent
  has_one :organization_cutoff, foreign_key: :organization_type, primary_key: :organization_type,
                                inverse_of: :organizations
  # rubocop:enable Rails/HasManyOrHasOneDependent

  has_many :requests, dependent: :restrict_with_error
  has_many :archived_requests, dependent: :restrict_with_error

  has_many :unit_requests, dependent: :restrict_with_error, class_name: 'Request', foreign_key: :unit_id,
                           inverse_of: :unit
  has_many :archived_unit_requests, dependent: :restrict_with_error,
                                    class_name: 'ArchivedRequest', foreign_key: :unit_id, inverse_of: :unit

  def requests_count
    unit? ? unit_requests.count : attributes['requests_count']
  end

  def archived_requests_count
    unit? ? archived_unit_requests.count : attributes['archived_requests_count']
  end

  has_many :roles, dependent: :delete_all
  validates_associated :roles
  accepts_nested_attributes_for :roles, reject_if: :all_blank, allow_destroy: true
  has_many :users, through: :roles

  validates :code, :organization_type, :name, presence: true
  validates :code, uniqueness: { scope: :organization_type }

  validate :only_one_root, :no_edits_if_archive

  # this makes sure we only have one root record
  def only_one_root
    return if organization_type != 'root'

    org =  Organization.find_by(organization_type: Organization.organization_types[:root])
    return if org.nil? || org.id == id

    errors.add(:organization_type, 'There can be only one root')
  end

  # this makes an org immutable if in archive. We can only activate/deactivate
  def no_edits_if_archive
    uneditable = changes.keys & UNEDITABLE_IF_ARCHIVED
    return unless persisted?
    return unless archived_records?
    return if uneditable.empty?

    uneditable.each do |k|
      msg = "#{description} has #{archived_requests.count} in the archive. Editing #{k} is not allowed."
      errors.add(k.intern, msg)
    end
  end

  def archived_records?
    if organization_type == 'unit'
      ArchivedRequest.where(unit_id: id).count.positive?
    else
      archived_requests_count.positive?
    end
  end

  def cutoff?
    return false unless organization_cutoff

    Time.zone.today > organization_cutoff.cutoff_date
  end

  def active?
    !cutoff? && !deactivated?
  end

  # the name of the record used in the json expression
  def text
    icon = if cutoff?
             'ban-circle'
           elsif deactivated?
             'remove-circle'
           else
             'ok-circle'
           end
    "#{name} (#{code}) <i class='glyphicon glyphicon-#{icon}'></i>"
  end

  def grandchildren
    children.map(&:children).flatten || []
  end

  def great_grandchildren
    grandchildren.map(&:children).flatten || []
  end

  # returns an array of the organizations up the tree
  def ancestors
    mom = parent
    ancestors = []
    while mom
      ancestors << mom
      mom = mom.parent
    end
    ancestors
  end

  def type_icon
    "glyphicon glyphicon-#{TYPE_MAPPING[organization_type]}"
  end

  def description
    "#{name} ( #{organization_type} )"
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  def index
    authorize Organization
    @organizations = Organization.all
    respond_to do |format|
      format.html
      format.json { render json: Organization.all.to_json }
    end
  end

  def new
    authorize Organization
    @organizations = Organization.all
    @organization = Organization.new(organization_id: Organization.root_org.id)
  end

  def show
    authorize Organization
    @organizations = Organization.all
    @organization = Organization.find(params[:id])
  end

  def edit
    authorize Organization
    @organizations = Organization.all
    @organization = Organization.includes(:parent, :roles).find(params[:id])
  end

  def update
    authorize Organization
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organizations_url, notice: "Organization #{@organization.name} was successfully updated." }
      else
        format.html { render :edit, error: @organization.errors }
      end
    end
  end

  def create
    authorize Organization
    @organization = Organization.new(organization_params)
    respond_to do |format|
      if @organization.save(organization_params)
        format.html { redirect_to organizations_url, notice: "Organization #{@organization.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /review_status/1
  def destroy
    authorize Organization
    @organization = Organization.find(params[:id])
    if @organization.destroy
      flash[:notice] = "Organization #{@organization.name} was successfully deleted."
    else
      flash[:error] = "ERROR Deleting #{@organization.name} #{@organization.errors}"
    end
    respond_to do |format|
      format.html { redirect_to organizations_url }
    end
  end

  private

    def organization_params
      params.require(:organization).permit(:code, :name, :organization_type, :deactivated,
                                           :organization_id, roles_attributes: %i[id user_id _destroy])
    end
end

app/views/organizations/_form.erb
<div class='container'>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= simple_form_for(@organization) do |f| %>
        
        <div class="page-header">
          <h2><%= @organization.name || "New Organization" %> 
              <div class='pull-right'> 
                <%= link_to 'Back', organizations_path, class: 'btn btn-default' %>
                <%= f.submit 'Save', class: 'btn btn-success' %>
              </div>
          </h2>
        </div>
        
          <div class='alert alert-info' role='alert'>
            <h4>
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              
              <% if @organization.organization_cutoff %>
              Request Cutoff is set to <%= @organization.organization_cutoff.cutoff_date %>
            <% end %>
            <div class='label label-info pull-right'>Active Records:<span class='badge'> <%= @organization.requests_count %></span></div> 
            <div class='label label-primary pull-right'>Archived Records:<span class='badge'> <%= @organization.archived_requests_count %></span></div></h4>
          </div>
          <% if @organization.archived_records? %> 
            <div class='alert alert-warning' role='alert'>
              <h4>
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <%= @organization.name %> has records that have been archived. It is not possible to change it's name,
              code, organization type, or parent
            </div>
          <% end %>     
        <%= render 'shared/form_errors', errors: @organization.errors %>
          
          
          <div class='panel panel-default'>
            <div class="panel-body">
              <%= f.input :name, disabled: @organization.archived_records? %>
              <%= f.input :code, disabled: @organization.archived_records? %>
              <%= f.input :organization_type, as: :select, 
                collection:  Organization.organization_types.keys.reject { |o| o == 'root' },
                disabled: ( f.object.root? || f.object.archived_records? ) %>
              <% unless @organization.organization_type == 'root' %> 
                <div class="input"> 
                  <%= f.label :parent %>
                  <% if @organization.parent %>
                    <%= link_to( @organization.parent.description, @organization.parent, { id: "parent_link" }) %>
                  <% else %>
                    <a href="#" id="parent_link" />
                  <% end %>
                    
                  <%= f.hidden_field :organization_id %> 
                  <button type="button" class="btn btn-info" <%= 'disabled' if @organization.archived_records? or !edit_or_new? %> 
                      data-toggle="modal" data-target="#orgModal">Select Parent</button> 
                </div>
              <% end %> 
              <%= f.input :deactivated, as: :hidden %>
              <div class='input'> 
                <label class='string optional' for='deactivated'>Deactivated</label>
                <div class="btn-group btn-toggle"> 
                  <button class="btn toggle-yes <%= @organization.deactivated? ? 'off' : 'on' %>" <%= 'disabled' if !edit_or_new? %>>Active</button>
                  <button class="btn toggle-no <%= @organization.deactivated? ? 'on' : 'off' %>" <%= 'disabled' if !edit_or_new? %>>Deactive</button>
                </div>
              </div>
            </div>
          </div>
            
          <div class='panel panel-default'>
            <div class="panel-heading"><span>Members</span>
              <% if edit_or_new? %> 
                <span class='pull-right'>
                  <%= link_to_add_association(	f, :roles,
                                              { class: "add-roles", 
                                                "data-association-insertion-node": "#roles",
                                                "data-association-insertion-method": 'append'}) do  %>
                                                            <i class='glyphicon glyphicon-plus-sign'></i>Add Member 
                  <% end %>
                </span>
              <% end %>
            </div>
            <div class="panel-body" id="roles">
              <%= f.fields_for :roles, f.object.roles do |role| %>
                  <%= render 'role_fields', f: role %>
              <% end %>
            </div>
          </div>
          
        <% end %>


    <% @organization.ancestors.each do |ancestor| %>
      <div class='panel panel-default'>
        <div class="panel-heading"><span>Users with access from <%= link_to ancestor.description, ancestor %></span>
        </div>
          
        <div class="panel-body" id="roles">
          <ul>
            <% ancestor.users.each do |u| %>
              <li><%= link_to u.description, u %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>




    </div>
  </div>
</div>

<!-- Modal -->
<div id="orgModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Organizations</h4>
      </div>
      <div class="modal-body">
        <div class='container' id="tree" ></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'organization_tree' %>

app/views/organizations/_organization_tree.erb
<%= javascript_tag do %>
  var treeData = <%=  @organizations.to_json.html_safe %>;
  var action = '<%= params['action'] %>';
  (function($){
    new OrganizationTree(treeData, action);
  })(jQuery); 
<% end %>

app/views/organizations/_role_fields.html.erb
<div class='role nested-fields'>
 	<%= link_to_remove_association("remove", f, { class: 'pull-right remove-role' }) unless !edit_or_new?  %> 
 	<% if f.object.user %> 
	  <div class="input">	
			<label>User</label>	
			<%= link_to( f.object.user.name, user_path(f.object.user)) %>	
		</div>	
	<% else %>
		<%= f.input :user_id, collection: User.all, label_method: :name,
			value_method: :id,  as: :select, required: true %>
	<% end %>
</div>

app/views/organizations/edit.html.erb
<div class='container'>
  <div class="row">
      <%= render partial: 'form' %>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="page-header">                                                                                                                                                                                   
  <h1>Organizations
    <span class='pull-right'><%= link_to( "New", new_organization_path, class: "btn btn-success" ) %></span>
  </h1>                                                                                                                                                                                        
</div>                                                                                                                                                                                                      


<div class='container org-tree'>
  
  <div class="col-md-3 pull-left org-info">
    <h3><span class='label label-info'>Icons:</span></h3> 
        <ul><% Organization::TYPE_MAPPING.each do |v, k| %>
          <li><%= v %> = <i class='glyphicon glyphicon-<%= k %>'></i></li>
        <% end %>
        <li>active = <i class='glyphicon glyphicon-ok-circle'></i></li> 
        <li>cutoff = <i class='glyphicon glyphicon-ban-circle'></i></li> 
        <li>deactive = <i class='glyphicon glyphicon-remove-circle'></i></li> 
        </ul>
        <h3><span class='label label-info'>Cutoff Dates:</span></h3> 
        <ul><% OrganizationCutoff.all.each do |oc| %>
          <li><%= oc.organization_type %> : <%= oc.cutoff_date %></li>
        <% end %></ul>
  </div>

  <div class='col-md-9' id="tree" ></div>
</div>

<%= render partial: 'organization_tree' %>

app/views/organizations/new.html.erb
<%= render partial: 'form' %>

app/views/organizations/show.html.erb
<div class='container readonly'>
  <div class="row">
    <%= render partial: "form" %>
  </div>
</div>