config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get '/my_requests' => 'home#index'

  resources :contractor_requests
  resources :labor_requests
  resources :staff_requests

  resources :users
  get '/logout' => 'users#logout'
  get 'impersonate/user/:user_id' => 'impersonate#create', as: :impersonate_user
  delete 'impersonate/revert' => 'impersonate#destroy', as: :revert_impersonate_user

  resources :organizations
  resources :organization_cutoffs
  resources :review_statuses
  resources :links

  resources :reports
  get '/reports/:id/download' => 'reports#download', as: :report_download

  get '/ping' => 'ping#verify'
end

app/views/layouts/_impersonate.html.erb
<% if impersonating_user? %>
  <div class="impersonate">
    <%= form_tag revert_impersonate_user_url, :method => :delete do %>
      Currently Impersonating: <%= impersonated_user.cas_directory_id %>
      <button type = "submit" class='btn btn-link'>Click To Stop impersonation</button>
    <% end %>
  </div>
<% end %>

app/views/layouts/_link.html.erb
<li class='help-link'>
  <% if current_user.admin? %>
    <i class='glyphicon glyphicon-remove-sign remove-link pull-left'></i>
  <% end %>
  <%=  link_to(link.text, link.url, target: "_blank", class: "pull-right") %> 
</li>

app/views/layouts/application.html.erb
<% provide :app_name, 'Annual Staffing Requests' %>
<% provide :container_class, impersonating_user? ? "container-fluid impersonate-extra-padding-top" : "container-fluid" %>
<% content_for :navbar do %>
  <ul class="nav navbar-nav">
    <li class="<%= 'active' if current_page?(labor_requests_path) %>"><%= link_to 'Labor and Assistance', labor_requests_path %></li>
    <li class="<%= 'active' if current_page?(staff_requests_path) %>"><%= link_to 'Staff', staff_requests_path %></li>
    <li class="<%= 'active' if current_page?(contractor_requests_path) %>"><%= link_to 'Salaried Contractor', contractor_requests_path %></li>
    <% if current_user %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Profile', current_user %></li>
          <li><%= link_to 'Sign Out', logout_path %></li>
          <li><%= link_to "My Requests", my_requests_path %></li> 
          <% if current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Manage Users', users_path %></li>
            <li><%= link_to 'Manage Organizations', organizations_path %></li>
            <li><%= link_to 'Manage Cutoff Dates', organization_cutoffs_path %></li>
            <li><%= link_to 'Manage Review Statuses', review_statuses_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Reports', reports_path %></li>
            <li role="separator" class="divider"></li>
            <li id='impersonate_user'><%= link_to 'Impersonate User', users_path %></li>
          <% end %>
            <li role="separator" class="divider"></li>
            <li class='text-center'><small>App Version: <%= APP_VERSION %></small></li>
        </ul>
      </li>
    <% end %>
    <li class='dropdown'>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Help
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% @links.each do |link| %>
            <li class='help-link'>
              <%=  link_to(link.text, link.url, target: "_blank", class: "") %>
            </li>
          <% end %>
          <% if current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Edit Links",links_url,class: "btn btn-success pull-right edit-links") %></li>
          <% end %>
        </ul>
    </li>
  </ul>
<% end %>
<% content_for :navbar_banner do %>
  <%= render 'layouts/impersonate' %>
<% end %>
<%= render 'layouts/umd_lib' %>